// Replay driver for data/fuzz/crashes/retry_tick/retry_tick_20260325_135647_w0
// Sequence generated by fuzzer that trigerring the even_idle_cpu
#include "driver.h"
#include "internal.h"
#include "op_handler.h"

struct replay_op {
  enum kstep_op_type type;
  int a;
  int b;
  int c;
};

static const struct replay_op ops[] = {
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_CREATE, 0, 0, 0},   // create task 0
    {OP_TASK_WAKEUP, 0, 0, 0},   // wake task 0
    {OP_TASK_CREATE, 1, 0, 0},   // create task 1
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_FORK, 0, 2, 0},     // fork task 0 into slot 2
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_WAKEUP, 1, 0, 0},   // wake task 1
    {OP_TASK_CREATE, 3, 0, 0},   // create task 3
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_CREATE, 4, 0, 0},   // create task 4
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_CREATE, 5, 0, 0},   // create task 5
    {OP_TASK_FIFO, 2, 0, 0},     // switch task 2 to FIFO
    {OP_TASK_WAKEUP, 5, 0, 0},   // wake task 5
    {OP_TASK_WAKEUP, 4, 0, 0},   // wake task 4
    {OP_TASK_CREATE, 6, 0, 0},   // create task 6
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_FIFO, 2, 0, 0},     // switch task 2 to FIFO
    {OP_TASK_CREATE, 7, 0, 0},   // create task 7
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_CREATE, 8, 0, 0},   // create task 8
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_WAKEUP, 7, 0, 0},   // wake task 7
    {OP_TASK_WAKEUP, 6, 0, 0},   // wake task 6
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_PIN, 1, 2, 4},      // pin task 1 to CPUs 2-4
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_CREATE, 9, 0, 0},   // create task 9
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_PIN, 0, 2, 4},      // pin task 0 to CPUs 2-4
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_PIN, 2, 1, 1},      // pin task 2 to CPU 1
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TICK, 0, 0, 0},          // advance one scheduler tick
    {OP_TASK_PAUSE, 2, 0, 0},    // pause task 2
    {OP_TASK_PAUSE, 6, 0, 0},    // pause task 6
};

static void setup(void) { 
  
  kstep_cpu_set_capacity(1, SCHED_CAPACITY_SCALE);
  kstep_cpu_set_capacity(2, SCHED_CAPACITY_SCALE / 2);
  kstep_cpu_set_capacity(3, SCHED_CAPACITY_SCALE);
  kstep_cpu_set_capacity(4, SCHED_CAPACITY_SCALE / 2);

  kstep_topo_init();
  const char *cls[] = {"0", "1-2", "1-2", "3-4", "3-4"};
  kstep_topo_set_cls(cls, ARRAY_SIZE(cls));
  kstep_topo_apply();

  kstep_cov_init(); 
}

static void run(void) {
  int i;

  TRACE_INFO("Replaying %zu ops from retry_tick_20260325_135647_w0",
             ARRAY_SIZE(ops));
  TRACE_INFO("Expected issue: TASK_PAUSE(task=7) stays blocked because task 7 remains runnable");

  for (i = 0; i < ARRAY_SIZE(ops); i++) {
    while (!kstep_execute_op(ops[i].type, ops[i].a, ops[i].b, ops[i].c))
      continue;
  }

  for (i = 0; i < 1000; i++) {
    kstep_execute_op(OP_TICK, 0, 0, 0);
  }
}

KSTEP_DRIVER_DEFINE{
    .name = "replay_retry_tick_135647_w0",
    .setup = setup,
    .run = run,
    .on_tick_begin = kstep_output_nr_running,
    .step_interval_us = 10000,
};

