name: Build QEMU
description: Restore from cache, or build and cache QEMU.

outputs:
  install_path:
    description: Where QEMU is installed
    value: data/qemu/install
  key:
    description: Cache key for the QEMU build
    value: qemu

runs:
  using: composite
  steps:
    - id: cache
      uses: actions/cache/restore@v4
      with:
        path: data/qemu/install
        key: qemu
        lookup-only: true

    - if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: sudo apt update && sudo apt install -y libglib2.0-dev ninja-build

    - if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: ./scripts/build_qemu.py

    - if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: data/qemu/install
        key: qemu
