obj-m := kmod.o
kmod-y := $(patsubst $(src)/%.c,%.o,$(filter-out %.mod.c,$(wildcard $(src)/*.c) $(wildcard $(src)/drivers/*.c)))
ccflags-y := -I$(srctree) -I$(src) -std=gnu11 -Werror -Wno-declaration-after-statement
