#ifndef KSTEP_USER_H
#define KSTEP_USER_H

enum sigcode {
  SIGCODE_WAKEUP,
  SIGCODE_FORK,
  SIGCODE_FORK_PIN,
  SIGCODE_SLEEP,
  SIGCODE_EXIT,
  SIGCODE_PAUSE,
  SIGCODE_SET_PRIO,
  SIGCODE_PIN,
  SIGCODE_FIFO,
};

#define TASK_READY_COMM "ready"
#endif
