name: LTS
on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # Every week

jobs:
  test:
    name: Linux 6.1
    uses: ./.github/workflows/main.yml
    with:
      version: v6.1.158
