name: LTS
on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # Every week

jobs:
  test:
    name: Linux 6.12
    uses: ./.github/workflows/main.yml
    with:
      version: v6.12.60
