name: CI

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Every week

env:
  QEMU_CACHE_KEY: qemu-10.2.0
  QEMU_INSTALL_PATH: data/qemu/install

jobs:
  qemu:
    name: Build QEMU
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        id: qemu-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.QEMU_INSTALL_PATH }}
          key: ${{ env.QEMU_CACHE_KEY }}
          lookup-only: true

      - name: Install QEMU
        if: steps.qemu-cache.outputs.cache-hit != 'true'
        run: ./install_deps.py ci-qemu

      - name: Save cache
        if: steps.qemu-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.QEMU_INSTALL_PATH }}
          key: ${{ env.QEMU_CACHE_KEY }}

  test:
    needs: qemu
    strategy:
      matrix:
        version: # LTS versions at https://kernel.org/
          - v6.18
          - v6.12
          - v6.6
          - v6.1
          - v5.15

    name: Linux ${{matrix.version}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Linux - Restore cache
        id: linux-cache
        uses: actions/cache/restore@v4
        with:
          path: linux
          key: ${{matrix.version}}-${{hashFiles('linux/config.kstep')}}

      - name: Linux - Download
        if: steps.linux-cache.outputs.cache-hit != 'true'
        run: ./checkout_linux.py ${{matrix.version}} --tarball

      - name: Linux - Install build dependencies
        if: steps.linux-cache.outputs.cache-hit != 'true'
        run: ./install_deps.py ci-linux

      - name: Linux - Build
        if: steps.linux-cache.outputs.cache-hit != 'true'
        run: make linux && make -C linux clean

      - name: Linux - Save cache
        if: steps.linux-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: linux
          key: ${{matrix.version}}-${{hashFiles('linux/config.kstep')}}

      - name: Build kSTEP
        run: make kstep

      - name: Install QEMU
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.QEMU_INSTALL_PATH }}
          key: ${{ env.QEMU_CACHE_KEY }}
          fail-on-cache-miss: true

      - name: Run kSTEP
        timeout-minutes: 1
        run: ./run.py

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v6
        with:
          path: data/logs/latest.log
          name: ${{matrix.version}}.log
          if-no-files-found: error

      - name: Write job summary
        run: echo "[${{matrix.version}}.log](${{steps.upload-artifact.outputs.artifact-url}})" >> $GITHUB_STEP_SUMMARY
