name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Linux ${{ matrix.linux_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux_version: ["6.6", "6.14"]

    steps:
    - uses: actions/checkout@v4

    - name: Restore Linux cache
      id: restore-cache
      uses: actions/cache@v4
      with:
        path: linux/current
        key: ${{ matrix.linux_version }}

    - name: Download Linux
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p linux/current
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ matrix.linux_version }}.tar.xz -O linux.tar.xz
        tar -xvf linux.tar.xz -C linux/current --strip-components=1

    - name: Build Linux
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt update && sudo apt install -y libelf-dev
        ./make_linux.py

    - name: Build kernel module
      run: make -C kmod

    - name: Install QEMU
      run: sudo apt update && sudo apt install -y qemu-kvm

    - name: Run QEMU
      timeout-minutes: 1
      run: ./run_qemu.py
