name: CI

on:
  workflow_call:
    inputs:
      version:
        description: "Linux version"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      version:
        description: "Linux version"
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Linux - Restore cache
        id: linux-cache
        uses: actions/cache/restore@v4
        with:
          path: linux
          key: ${{inputs.version}}-${{hashFiles('linux/config.kstep')}}

      - name: Linux - Download
        if: steps.linux-cache.outputs.cache-hit != 'true'
        run: ./checkout_linux.py ${{inputs.version}} --tarball

      - name: Linux - Install build dependencies
        if: steps.linux-cache.outputs.cache-hit != 'true'
        run: ./install_deps.py ci-linux

      - name: Linux - Build
        if: steps.linux-cache.outputs.cache-hit != 'true'
        run: make linux

      - name: Linux - Save cache
        if: steps.linux-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: linux
          key: ${{inputs.version}}-${{hashFiles('linux/config.kstep')}}

      - name: Build kSTEP
        run: make kstep

      - name: QEMU - Restore cache
        id: qemu-cache
        uses: actions/cache/restore@v4
        with:
          path: data/qemu
          key: qemu

      - name: QEMU - Install
        if: steps.qemu-cache.outputs.cache-hit != 'true'
        run: ./install_deps.py ci-qemu

      - name: QEMU - Save cache
        if: steps.qemu-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: data/qemu
          key: qemu

      - name: Run kSTEP
        timeout-minutes: 1
        run: ./run.py
