name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y linux-headers-$(uname -r)

    - name: Build kernel module
      run: make kmod
