name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build on Linux ${{ matrix.linux_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux_version: [6.0, 6.6, 6.14]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libelf-dev

    - name: Download Linux
      run: |
        mkdir -p linux/current
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ matrix.linux_version }}.tar.xz -O linux.tar.xz
        tar -xvf linux.tar.xz -C linux/current --strip-components=1

    - name: Prepare Linux
      run: ./make_linux.py --modules_prepare

    - name: Build kernel module
      run: make -C kmod obj
